# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD

on:
  push:
    branches: [arrahm/add-cd]
  # pull_request:
  #   branches: [main]
# on: [workflow_dispatch]

jobs:
  build:
    name: Run CI on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: woke
        uses: get-woke/woke-action-reviewdog@v0
        with:
          fail-on-error: true
          level: error
          reporter: github-pr-review
          filter-mode: added
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          fail_on_error: true
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install
        run: npm ci --ignore-scripts
      - name: Eslint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          CI: true
  publish:
    if: github.ref == 'refs/heads/arrahm/add-cd'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "CI: bumps version to {{version}} [skip ci]"
          target-branch: "arrahm/add-cd"
      - name: Publish
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${PACKAGE_TOKEN}
          npm publish --ignore-scripts
        env:
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
